converter:
  build: .
  volumes:
    - .:/data
#    - ./data:/usr/share/nginx/html
  links:
    - postgis

#web:
#  image: nginx
#  ports:
#    - "6080:80"
#  volumes:
#    - ./nginx:/etc/nginx/conf.d
#  volumes_from:
#    - converter

postgis:
  image: mdillon/postgis:9.4
  environment:
    - POSTGRES_PASSWORD=aufgrabungen123
  volumes:
    - ./postgis:/var/lib/postgresql/data
